version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@8.6.0
  #slack: circleci/slack@4.12.1

parameters:
  #alerts-slack-channel:
  #  type: string
    # Normally team specific alert channel e.g. hmpps_tech_alerts, syscon-alerts, dps_sed_alerts
    # This is to avoid a general alert dumping ground that no-one then monitors
    #default: hmpps_typescript_notifications

  #releases-slack-channel:
  #  type: string
    # Normally dps-releases for most teams / projects
  #  default: hmpps_typescript_notifications

  node-version:
    type: string
    default: 18.15-browsers

jobs:
  runner:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - run:
          command: |
            npm i
            npx playwright i --with-deps
            npm start
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - runner:
          filters:
            branches:
              only:
                - main
     