import test, { expect } from "@playwright/test";
import courtHearingGenerator from "./courtHearingRequestGenerator";
import { simpleDefinedTest } from "@data/testUtils";
import { Sheffield } from "./courtCentres.data";
import { InitiationCode, JurisdictionType } from "./courtHearingRequest.d";
import moment from "moment";

test.describe('Court Hearing Request Generator', async () => {
    const sut = courtHearingGenerator()

    test.describe('Default fields without options', async () => {
        const result = sut.generate()

        expect(result.hearing).toBeDefined()
        const hearing = result.hearing

        simpleDefinedTest('Id', hearing.id)

        test.describe('Court Centre', async () => {
            const courtCentre = hearing.courtCentre
            
            simpleDefinedTest('Id', courtCentre.id)
            test('Code', async () => {
                expect(courtCentre.code).toEqual(Sheffield.code)
            })
            test('Name', async () => {
                expect(courtCentre.name).toEqual(Sheffield.name)
            })
            simpleDefinedTest('Room Id', courtCentre.roomId)
            simpleDefinedTest('Room Name', courtCentre.roomName)            
        })
        test.describe('Type', async () => {
            const hearingType = hearing.type

            simpleDefinedTest('Id', hearingType.id)
            simpleDefinedTest('Description', hearingType.description)
        })
        test('Jusrisdiction Type', async () => {
            expect(hearing.jurisdictionType).toEqual(JurisdictionType.MAGISTRATES)
        })
        test.describe('Hearing Days', async () => {
            const hearingsDays = hearing.hearingDays

            expect(hearingsDays).toHaveLength(1)

            test.describe('Default hearing day', async () => {
                const hearingDay = hearingsDays.at(0)

                test('Listed Duration Minutes', async () => {
                    expect(hearingDay.listedDurationMinutes).toBeDefined()
                    expect(hearingDay.listedDurationMinutes).toBeGreaterThanOrEqual(10)
                    expect(hearingDay.listedDurationMinutes).toBeLessThanOrEqual(60)
                    expect(hearingDay.listedDurationMinutes % 10).toEqual(0)
                })
                test('Sitting Day', async () => {
                    const expectedSitting = moment().set('hour', 9).set('minutes', 0).set('seconds', 0).set('milliseconds', 0).toISOString()
                    expect(hearingDay.sittingDay).toBeDefined()
                    expect(hearingDay.sittingDay).toEqual(expectedSitting)
                })
            })
        })
        test.describe('Prosecution Cases', async () => {
            const prosecutionCases = hearing.prosecutionCases

            expect(prosecutionCases).toHaveLength(1)

            test.describe('Default Prosecution Case', async () => {
                const prosecutionCase = prosecutionCases.at(0)

                simpleDefinedTest('Id', prosecutionCase.id)
                test('Initiation Code', async () => {
                    expect(prosecutionCase.initiationCode).toBeDefined()
                    expect(prosecutionCase.initiationCode).toEqual(InitiationCode.Charge)
                })
                test.describe('Prosecution Case Identifier', async () => {
                    const prosecutionCaseIdentifier = prosecutionCase.prosecutionCaseIdentifier

                    simpleDefinedTest('Prosecution Authority Id', prosecutionCaseIdentifier.prosecutionAuthorityId)
                    test('Prosecution Authority Code', async () => {
                        expect(prosecutionCaseIdentifier.prosecutionAuthorityCode).toBeDefined()
                        expect(prosecutionCaseIdentifier.prosecutionAuthorityCode).toEqual("CPS")
                    })
                    test('Case URN', async () => {
                        expect(prosecutionCaseIdentifier.caseURN).toBeDefined()
                        expect(prosecutionCaseIdentifier.caseURN).toMatch(/^\d{2}\w{2}\d{8}$/)
                    })
                })
                test.describe('Defendants', async () => {
                    const defendants = prosecutionCase.defendants

                    expect(defendants).toHaveLength(1)

                    test.describe('Default Defendant', async () => {
                        const defendant = defendants.at(0)

                        simpleDefinedTest('Id', defendant.id)
                        test.describe('Offences', async () => {
                            const offences = defendant.offences

                            expect(offences).toHaveLength(1)

                            test.describe('Default Offence', async () => {
                                /**
                                 * Generated by the OffenceGenerator so details passed over
                                 * to that test suite
                                 */
                                simpleDefinedTest('Offence', offences.at(0))
                            })
                        })
                        simpleDefinedTest('Prosecution Case Id', defendant.prosecutionCaseId)
                        test.describe('Person Defendant', () => {
                            expect(defendant.personDefendant).toBeDefined()

                            test.describe('Person Details', async () => {
                                const personDetails = defendant.personDefendant.personDetails

                                test.describe('Default Person Details', async () => {
                                    /**
                                     * Generated by the PersonGenerator so details passed over
                                     * to that test suite
                                     */
                                    simpleDefinedTest('Person Detail', personDetails)
                                })
                            })
                        })
                    })
                })
            })
        })
    })
})